### ISSUE TITLE
Filters don't work after upgrading to v2.1.2

### ISSUE THREAD

**Issue by Tony-MF** [plausible/hosting#159]
Hello,

After clicking on it, nothing happens. 
<img width="320" alt="image" src="https://github.com/user-attachments/assets/6762202e-ab58-4649-bdd4-f6ee5afeb958">

In JS console it shows:

`dashboard-1e2f54168f06dc71b6c54356a023ba4b.js?vsn=d:19 Uncaught TypeError: window.trackCustomEvent is not a function`

**Comment by ruslandoga** [comment]
👋 @Tony-MF 

Should be fixed with https://github.com/plausible/analytics/pull/4627

It's part of the new v2.1.3: https://github.com/plausible/analytics/discussions/4629
